# Generated by Django 3.2.8 on 2024-03-10 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20240309_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autor_id',
            new_name='autor',
        ),
    ]
